name: 'LLM Prompt Action'
description: 'Calls StackSpot LLM API with OAuth authentication'
author: 'Your Name'

inputs:
  tenant:
    description: 'StackSpot tenant identifier'
    required: true
  client_id:
    description: 'OAuth client ID'
    required: true
  client_secret:
    description: 'OAuth client secret'
    required: true
  conversation_id:
    description: 'Conversation identifier'
    required: true
  agent_id:
    description: 'Agent identifier'
    required: true
  user_prompt:
    description: 'User prompt for the LLM'
    required: true

outputs:
  response:
    description: 'LLM response text'
    value: ${{ steps.llm.outputs.response }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        TENANT=$(echo '${{ toJSON(inputs.tenant) }}' | jq -r '.')
        CLIENT_ID=$(echo '${{ toJSON(inputs.client_id) }}' | jq -r '.')
        CONVERSATION_ID=$(echo '${{ toJSON(inputs.conversation_id) }}' | jq -r '.')
        AGENT_ID=$(echo '${{ toJSON(inputs.agent_id) }}' | jq -r '.')
        USER_PROMPT=$(echo '${{ toJSON(inputs.user_prompt) }}' | jq -r '.')
        
        if [[ -z "$TENANT" || -z "$CLIENT_ID" || -z "$CONVERSATION_ID" || -z "$AGENT_ID" || -z "$USER_PROMPT" ]]; then
          echo "Error: All required inputs must be provided"
          exit 1
        fi

    - name: Get OAuth Token
      id: oauth
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Requesting OAuth token..."
        response=$(curl --fail --silent --location \
          --request POST "https://idm.stackspot.com/${{ inputs.tenant }}/oidc/oauth/token" \
          --header 'Content-Type: application/x-www-form-urlencoded' \
          --data-urlencode "client_id=${{ inputs.client_id }}" \
          --data-urlencode 'grant_type=client_credentials' \
          --data-urlencode "client_secret=${{ inputs.client_secret }}")
        
        if ! token=$(echo "$response" | jq -r '.access_token // empty'); then
          echo "Error: Failed to parse access token from response"
          exit 1
        fi
        
        if [[ -z "$token" || "$token" == "null" ]]; then
          echo "Error: No access token received"
          exit 1
        fi
        
        echo "::add-mask::$token"
        echo "token=$token" >> $GITHUB_OUTPUT

    - name: Call LLM API and Set Output
      id: llm
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Calling LLM API..."
        
        # Escape user prompt for JSON
        user_prompt_escaped=$(echo '${{ inputs.user_prompt }}' | jq -Rs .)
        
        # Create the JSON payload
        payload=$(jq -nc \
          --arg conversation_id "${{ inputs.conversation_id }}" \
          --arg agent_id "${{ inputs.agent_id }}" \
          --argjson user_prompt "$user_prompt_escaped" \
          '{
            "context": {
              "conversation_id": $conversation_id,
              "upload_ids": [],
              "agent_id": $agent_id,
              "agent_built_in": true,
              "os": "github-action",
              "platform": "github-action",
              "platform_version": "1.0",
              "stackspot_ai_version": "2.4.0"
            },
            "user_prompt": $user_prompt
          }')
        
        echo "Payload: $payload"
        
        # Make the API call with timeout and better error handling
        timeout 300 curl --fail --silent --show-error \
          'https://genai-code-buddy-api.stackspot.com/v3/chat' \
          -H "accept: text/event-stream" \
          -H "authorization: Bearer ${{ steps.oauth.outputs.token }}" \
          -H "content-type: application/json" \
          --data-raw "$payload" \
          > stream_response.txt || {
            echo "Error: API call failed"
            if [[ -f stream_response.txt ]]; then
              echo "Stream response content:"
              cat stream_response.txt
            fi
            exit 1
          }
        
        echo "Raw stream response:"
        cat stream_response.txt
        
        # Process the stream response more carefully
        final_response=""
        while IFS= read -r line; do
          if [[ "$line" =~ ^data:\ (.+)$ ]]; then
            data_content="${BASH_REMATCH[1]}"
            if [[ -n "$data_content" && "$data_content" != "{}" ]]; then
              answer=$(echo "$data_content" | jq -r 'select(.answer != null) | .answer' 2>/dev/null || echo "")
              if [[ -n "$answer" ]]; then
                final_response="${final_response}${answer}"
              fi
            fi
          fi
        done < stream_response.txt
        
        echo "Final response: $final_response"
        
        # Set output using proper multiline format with unique delimiter
        delimiter="LLMRESPONSE_$(date +%s)_$$"
        {
          echo "response<<${delimiter}"
          echo "$final_response"
          echo "$delimiter"
        } >> $GITHUB_OUTPUT